/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.text_editor;

import java.awt.Font;
import javax.swing.undo.UndoManager;

/**
 *
 * @author Alex
 */
public class TEGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TEGUI.class.getName());

    /**
     * Creates new form TEGUI
     */
    public TEGUI() {
        initComponents();
        jTextfield.getDocument().addUndoableEditListener(undoManager);

    }
    private UndoManager undoManager = new UndoManager();
public boolean bold;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextfield = new javax.swing.JTextArea();
        jSAVEBT = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        jundo = new javax.swing.JButton();
        jredo = new javax.swing.JButton();
        jBold_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextfield.setColumns(20);
        jTextfield.setRows(5);
        jScrollPane1.setViewportView(jTextfield);

        jSAVEBT.setText("Save");
        jSAVEBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSAVEBTMousePressed(evt);
            }
        });
        jSAVEBT.addActionListener(this::jSAVEBTActionPerformed);

        jToolBar1.setRollover(true);

        jundo.setText("Undo");
        jundo.addActionListener(this::jundoActionPerformed);
        jToolBar1.add(jundo);

        jredo.setText("Redo");
        jredo.addActionListener(this::jredoActionPerformed);
        jToolBar1.add(jredo);

        jBold_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBold_btn.setText("Bold");
        jBold_btn.addActionListener(this::jBold_btnActionPerformed);
        jToolBar1.add(jBold_btn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSAVEBT)
                .addGap(91, 91, 91))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSAVEBT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSAVEBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSAVEBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSAVEBTActionPerformed

    private void jSAVEBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSAVEBTMousePressed
        //get text
        String text = jTextfield.getText();
        //ADD thing to save to database

    }//GEN-LAST:event_jSAVEBTMousePressed

    private void jundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jundoActionPerformed
        // TODO add your handling code here:
        if (undoManager.canUndo()) {
            undoManager.undo();
        }

    }//GEN-LAST:event_jundoActionPerformed

    private void jredoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jredoActionPerformed
        // TODO add your handling code here:
        if (undoManager.canRedo()) {
            undoManager.redo();
        }
    }//GEN-LAST:event_jredoActionPerformed

    private void jBold_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBold_btnActionPerformed
        // TODO add your handling code here:
        // get the curent font

        if (!bold) {
            Font currentFont = jTextfield.getFont();
            // make it bold based on what is currently in the text area
            Font boldFont = new Font(currentFont.getName(), Font.BOLD, currentFont.getSize());
            // next apply it
            jTextfield.setFont(boldFont);
        }


    }//GEN-LAST:event_jBold_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TEGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBold_btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSAVEBT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextfield;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jredo;
    private javax.swing.JButton jundo;
    // End of variables declaration//GEN-END:variables
}
