/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Text_editor_GUI;

import java.awt.Font;
import javax.swing.text.StyledEditorKit;
import javax.swing.undo.UndoManager;
import models.Note;


/**
 *
 * @author Alex
 */
public class TEGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TEGUI.class.getName());
    private String currentTitle;
    private String currentUser;
    private com.mycompany.text_editor.NotesService notesService = new com.mycompany.text_editor.NotesService();
    private UndoManager undoManager = new UndoManager();
    public boolean bold = false;
    public boolean italic = false;
    private javax.swing.Timer autoSaveTimer;
    /**
     * Creates new form TEGUI
     */
    public TEGUI(String title, String username) {
            initComponents();
            // 1. Tell the pane to handle HTML
            jTextPane1.setContentType("text/html");

            this.currentTitle = title;
            this.currentUser = username;

            // 2. Load content (which will now be HTML strings)
            loadNoteContent();
            autoSaveTimer = new javax.swing.Timer(15000,new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                System.out.println("Auto-saving..."); // Optional: for your console
                Save(false);
            }
        });

        autoSaveTimer.start();

            // 3. Attach UndoManager
            jTextPane1.getDocument().addUndoableEditListener(undoManager);

    }
    
    private void loadNoteContent() {
        Note note = notesService.getSpecificNote(currentTitle, currentUser);
        if (note != null) {
            // The text coming from the DB now contains <b> and <i> tags
            jTextPane1.setText(note.getFileContents());
        }
    }
    
    private void Save(boolean popUp) {
        java.io.StringWriter sw = new java.io.StringWriter();
        try {
            jTextPane1.getEditorKit().write(sw, jTextPane1.getDocument(), 0, jTextPane1.getDocument().getLength());
            String htmlContent = sw.toString();

            models.Note noteToSave = new models.Note(currentTitle, htmlContent, currentUser);
            notesService.SaveText(noteToSave);

            if (popUp) {
                javax.swing.JOptionPane.showMessageDialog(this, "File Saved!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSAVEBT = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSaveMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jUndo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jbold = new javax.swing.JMenuItem();
        jItalic = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSAVEBT.setText("Save");
        jSAVEBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSAVEBTMousePressed(evt);
            }
        });
        jSAVEBT.addActionListener(this::jSAVEBTActionPerformed);

        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(542, Short.MAX_VALUE)
                .addComponent(jSAVEBT)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSAVEBT, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jSaveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jSaveMenu.setText("Save");
        jSaveMenu.addActionListener(this::jSaveMenuActionPerformed);
        jMenu1.add(jSaveMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jUndo.setText("Undo");
        jUndo.addActionListener(this::jUndoActionPerformed);
        jMenu2.add(jUndo);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Redo");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jbold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jbold.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbold.setText("Bold");
        jbold.addActionListener(this::jboldActionPerformed);
        jMenu2.add(jbold);

        jItalic.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jItalic.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jItalic.setText("Italic");
        jItalic.addActionListener(this::jItalicActionPerformed);
        jMenu2.add(jItalic);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSAVEBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSAVEBTActionPerformed
        // TODO add your handling code here:
        Save(true);
        
    }//GEN-LAST:event_jSAVEBTActionPerformed

    private void jSAVEBTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSAVEBTMousePressed
        // Use an output stream to capture the HTML str

    }//GEN-LAST:event_jSAVEBTMousePressed

    private void jUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUndoActionPerformed
        // TODO add your handling code here:
        if (undoManager.canUndo()) {
            undoManager.undo();
        }

    }//GEN-LAST:event_jUndoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (undoManager.canRedo()) {
            undoManager.redo();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jboldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboldActionPerformed
        // TODO add your handling code here:
        // This looks at the highlighted text and toggles Bold
        new StyledEditorKit.BoldAction().actionPerformed(evt);
        jTextPane1.requestFocusInWindow();


    }//GEN-LAST:event_jboldActionPerformed

    private void jItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItalicActionPerformed
        // TODO add your handling code here:
        new StyledEditorKit.ItalicAction().actionPerformed(evt);
        jTextPane1.requestFocusInWindow();

    }//GEN-LAST:event_jItalicActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
      // Create a StringWriter to get the current HTML content exactly how it's saved
        if (autoSaveTimer != null) {
            autoSaveTimer.stop();
        }
        Save(true);

        WelcomePage welcome = new WelcomePage(this.currentUser);
        welcome.setVisible(true);
        this.dispose();
    


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jSaveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveMenuActionPerformed
        // TODO add your handling code here:
         Save(true);
    }//GEN-LAST:event_jSaveMenuActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TEGUI("title", "guest").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItalic;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSAVEBT;
    private javax.swing.JMenuItem jSaveMenu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem jUndo;
    private javax.swing.JMenuItem jbold;
    // End of variables declaration//GEN-END:variables
}
