/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Text_editor_GUI;

import com.mycompany.utils.Config;
import com.mycompany.text_editor.NotesService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Note;
import javax.swing.text.StyledEditorKit;
import java.io.StringWriter;

/**
 *
 * @author Alex
 */
public class WelcomePage extends javax.swing.JFrame {

    private javax.swing.DefaultListModel<String> listModel = new javax.swing.DefaultListModel<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomePage.class.getName());
    private NotesService notesService;
    private String username;
    private javax.swing.Timer autoSaveTimer;
    /**
     * Creates new form WelcomePage
     */
    
    
    public WelcomePage(String username) {
        initComponents();
        this.username = username;
        Config.getConnection();
        notesService = new NotesService();
              
        jNoteList.setModel(listModel);
        loadListData();
    }

    private WelcomePage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdelete = new javax.swing.JButton();
        jNewfileBT = new javax.swing.JButton();
        jcopy = new javax.swing.JButton();
        jsearchBTN = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNoteList = new javax.swing.JList<>();
        LogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel1.setText("User files");

        jdelete.setText("Delete");
        jdelete.addActionListener(this::jdeleteActionPerformed);

        jNewfileBT.setText("New file");
        jNewfileBT.addActionListener(this::jNewfileBTActionPerformed);

        jcopy.setText("Duplicate");
        jcopy.addActionListener(this::jcopyActionPerformed);

        jsearchBTN.setText("Search");
        jsearchBTN.addActionListener(this::jsearchBTNActionPerformed);

        jNoteList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jNoteList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNoteListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jNoteList);

        LogOut.setText("Log Out");
        LogOut.addActionListener(this::LogOutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jsearchBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNewfileBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcopy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LogOut)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdelete)
                    .addComponent(jcopy)
                    .addComponent(jNewfileBT)
                    .addComponent(jsearchBTN))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchBTNActionPerformed
        // TODO add your handling code here:
        //add search function
        String query = JOptionPane.showInputDialog(this, "Search for file title:");
        if (query != null) {
            listModel.removeAllElements(); // Clear the list
            List<Note> notes = notesService.getNotesByUser(this.username);
            for (Note note : notes) {
                if (note.getFileName().toLowerCase().contains(query.toLowerCase())) {
                    listModel.addElement(note.getFileName());
                }
            }
        }


    }//GEN-LAST:event_jsearchBTNActionPerformed

    private void jNewfileBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewfileBTActionPerformed
        String title = JOptionPane.showInputDialog("Enter the Note Title");
        if (title != null && !title.trim().isEmpty()) {
            Note note = new Note(title, "", this.username);
            notesService.CreateText(note);

            // No need to refresh here because we are closing this page
            TEGUI editor = new TEGUI(title, this.username);
            editor.setVisible(true);
            this.dispose();
        }
        //add new file function
    }//GEN-LAST:event_jNewfileBTActionPerformed

    private void jcopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcopyActionPerformed
        // TODO add your handling code here:
        //add copy function
        String originalTitle = jNoteList.getSelectedValue(); // Get from List, not Table
        if (originalTitle != null) {
            String newTitle = JOptionPane.showInputDialog(this, "Enter name for duplicate:", originalTitle + "_copy");
            if (newTitle != null && !newTitle.trim().isEmpty()) {
                Note originalNote = notesService.getSpecificNote(originalTitle, this.username);
                if (originalNote != null) {
                    Note duplicateNote = new Note(newTitle, originalNote.getFileContents(), this.username);
                    notesService.CreateText(duplicateNote);
                    loadListData(); // Refresh the list
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a file to duplicate first.");
        }
    }//GEN-LAST:event_jcopyActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        int selectedIndex = jNoteList.getSelectedIndex();
        if (selectedIndex != -1) {
            // Get the title from the first column of your table
            String title = jNoteList.getSelectedValue();

            int confirm = JOptionPane.showConfirmDialog(this, "Delete " + title + "?");
            if (confirm == JOptionPane.YES_OPTION) {
                notesService.DeleteNote(title, this.username);
                // Refresh table after deletion
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
        }
        loadListData();
        //add delete function
    }//GEN-LAST:event_jdeleteActionPerformed

    private void jNoteListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoteListMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) { 
        // Get the index of the item that was double-clicked
        int index = jNoteList.locationToIndex(evt.getPoint());
        
        if (index != -1) {
            String selectedTitle = jNoteList.getModel().getElementAt(index);
            
            // Switch to TEGUI
            TEGUI editor = new TEGUI(selectedTitle, this.username);
            editor.setVisible(true);
            editor.setLocationRelativeTo(this);
            this.dispose();
        }
    }
    }//GEN-LAST:event_jNoteListMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to Log Out??", "Log Out",
                    javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.NO_OPTION) {
            return; // Stay on the page
        }
        else{
            LoginPage l = new LoginPage();
            l.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void loadListData() {
        listModel.removeAllElements();
        jNoteList.setModel(listModel);

        List<Note> notes = notesService.getNotesByUser(this.username);
        for (Note note : notes) {
            // The title is usually plain text, so this stays simple
            listModel.addElement(note.getFileName());}
}
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WelcomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNewfileBT;
    private javax.swing.JList<String> jNoteList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jcopy;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jsearchBTN;
    // End of variables declaration//GEN-END:variables
}
