/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Text_editor_GUI;

import com.mycompany.utils.Config;
import com.mycompany.text_editor.NotesService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Note;

/**
 *
 * @author Alex
 */
public class WelcomePage extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomePage.class.getName());
    private NotesService notesService;
    private String username;
    /**
     * Creates new form WelcomePage
     */
    public WelcomePage(String username) {
        initComponents();
        this.username = username;
        Config.getConnection();
        notesService = new NotesService();
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
        });
        
        loadTableData();
    }

    private WelcomePage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jdelete = new javax.swing.JButton();
        jNewfileBT = new javax.swing.JButton();
        jcopy = new javax.swing.JButton();
        jsearchBTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel1.setText("User files");

        jdelete.setText("Delete");
        jdelete.addActionListener(this::jdeleteActionPerformed);

        jNewfileBT.setText("New file");
        jNewfileBT.addActionListener(this::jNewfileBTActionPerformed);

        jcopy.setText("Duplicate");
        jcopy.addActionListener(this::jcopyActionPerformed);

        jsearchBTN.setText("Search");
        jsearchBTN.addActionListener(this::jsearchBTNActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jsearchBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNewfileBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcopy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jdelete)
                    .addComponent(jcopy)
                    .addComponent(jNewfileBT)
                    .addComponent(jsearchBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jsearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchBTNActionPerformed
        // TODO add your handling code here:
        //add search function
        String query = JOptionPane.showInputDialog(this, "Search for file title:");
        if (query != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            List<Note> notes = notesService.getNotesByUser(this.username);
            for (Note note : notes) {
                if (note.getFileName().toLowerCase().contains(query.toLowerCase())) {
                    model.addRow(new Object[]{note.getFileName(), note.getFileContents()});
                }
            }
        }


    }//GEN-LAST:event_jsearchBTNActionPerformed

    private void jNewfileBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewfileBTActionPerformed
        String title = JOptionPane.showInputDialog("Enter the Note Title");
    
        // Check if user clicked cancel or entered nothing
        if (title != null && !title.trim().isEmpty()) {
            // Pass the title, initial empty content, and the current session username
            Note note = new Note(title, "", this.username); 
            notesService.CreateText(note);

            
    }
        loadTableData();
        //add new file function
    }//GEN-LAST:event_jNewfileBTActionPerformed

    private void jcopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcopyActionPerformed
        // TODO add your handling code here:
        //add copy function
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String originalTitle = jTable1.getValueAt(row, 0).toString();
            String newTitle = JOptionPane.showInputDialog(this, "Enter name for duplicate:", originalTitle + "_copy");

            if (newTitle != null && !newTitle.trim().isEmpty()) {
                // Fetch the original note content
                Note originalNote = notesService.getSpecificNote(originalTitle, this.username);

                if (originalNote != null) {
                    // Create a new note with the same content but new title
                    Note duplicateNote = new Note(newTitle, originalNote.getFileContents(), this.username);
                    notesService.CreateText(duplicateNote);
                    loadTableData(); // Refresh list
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select a file to duplicate first.");
        }
    }//GEN-LAST:event_jcopyActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // Get the title from the first column of your table
            String title = jTable1.getValueAt(selectedRow, 0).toString();

            int confirm = JOptionPane.showConfirmDialog(this, "Delete " + title + "?");
            if (confirm == JOptionPane.YES_OPTION) {
                notesService.DeleteNote(title, this.username);
                // Refresh table after deletion
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a file to delete.");
        }
        loadTableData();
        //add delete function
    }//GEN-LAST:event_jdeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public final void loadTableData() {
        // 1. Get the list of notes for the current user
        List<Note> notes = notesService.getNotesByUser(this.username);

        // 2. Access the table's model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // 3. Clear existing rows to avoid duplicates
        model.setRowCount(0);

        // 4. Define column headers (Title and Preview)
        model.setColumnIdentifiers(new String[]{"File Name", "Content Preview"});

        // 5. Add notes to the table
        for (Note note : notes) {
            String preview = note.getFileContents();
            // Shorten preview if it's too long
            if (preview.length() > 50) preview = preview.substring(0, 47) + "...";

            model.addRow(new Object[]{note.getFileName(), preview});
    }
}
    
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) { // Double-click detected
        int row = jTable1.getSelectedRow();
        if (row != -1) {
            String title = jTable1.getValueAt(row, 0).toString();

            // Create the editor, passing the selected title and current username
            TEGUI editor = new TEGUI(title, this.username);
            editor.setLocation(this.getLocation());
            editor.setVisible(true);

            // Close the welcome page
            this.dispose();
        }
    }    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WelcomePage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jNewfileBT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jcopy;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jsearchBTN;
    // End of variables declaration//GEN-END:variables
}
